import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/lib/auth";
import { Footer } from "@/components/Footer/Footer";

const montserrat = Montserrat({ 
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-montserrat',
});

const poppins = Poppins({ 
  subsets: ["latin"],
  display: 'swap',
  weight: ['600'],
  variable: '--font-poppins'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" className={`${montserrat.variable} ${poppins.variable} font-montserrat`}>
      <body>
        <SessionProvider session={session}>
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
